# Generated by Django 4.0.6 on 2022-07-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primera_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='articulo',
        ),
    ]
